apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceinstances.servicecatalog.k8s.io
  labels:
    svcat: "true"
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: servicecatalog.k8s.io
  scope: Namespaced
  names:
    plural: serviceinstances
    singular: serviceinstance
    kind: ServiceInstance
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              clusterServiceClassExternalName:
                type: string
              clusterServicePlanExternalName:
                type: string
              clusterServiceClassExternalID:
                type: string
              clusterServicePlanExternalID:
                type: string
              clusterServiceClassName:
                type: string
              clusterServicePlanName:
                type: string
              serviceClassExternalName:
                type: string
              servicePlanExternalName:
                type: string
              serviceClassExternalID:
                type: string
              servicePlanExternalID:
                type: string
              serviceClassName:
                type: string
              servicePlanName:
                type: string
              clusterServiceClassRef:
                type: object
                properties:
                  name:
                    type: string
              clusterServicePlanRef:
                type: object
                properties:
                  name:
                    type: string
              serviceClassRef:
                type: object
                properties:
                  name:
                    type: string
              servicePlanRef:
                type: object
                properties:
                  name:
                    type: string
              parameters:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              parametersFrom:
                type: array
                items:
                  type: object
                  properties:
                    secretKeyRef:
                      type: object
                      properties:
                        name: 
                          type: string
                        key: 
                          type: string
              externalID:
                type: string
              userInfo:
                  type: object
                  properties:
                    username:
                      type: string
                    uid:
                      type: string
                    groups:
                      type: array
                      items:
                        type: string
                    extra:
                      additionalProperties:
                        items:
                          type: string
                        type: array
                      type: object
              updateRequests:
                type: integer
                format: int64

          status:
            type: object
            properties:
              servicePlanName:
                type: array
                items: 
                  type: object
                  properties:
                    type: 
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string 
                    reason: 
                      type: string
                    message: 
                      type: string
              asyncOpInProgress:
                type: boolean
              orphanMitigationInProgress:
                type: boolean
              lastOperation:
                type: string
              dashboardURL:
                type: string
              currentOperation:
                type: string

              reconciledGeneration:
                type: integer
                format: int64
              observedGeneration:
                type: integer
                format: int64
              operationStartTime:
                format: date-time
                type: string
              inProgressProperties:
                type: object
                properties:
                  clusterServicePlanExternalName:
                    type: string
                  clusterServicePlanExternalID:
                    type: string
                  servicePlanExternalName:
                    type: string
                  servicePlanExternalID:
                    type: string
                  parameters:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  parameterChecksum:
                    type: string
                  userInfo:
                    type: object
                    properties:
                      username:
                        type: string
                      uid:
                        type: string
                      groups:
                        type: array
                        items:
                          type: string
                      extra:
                        additionalProperties:
                          items:
                            type: string
                          type: array
                        type: object
              externalProperties:
                type: object
                properties:
                  clusterServicePlanExternalName:
                    type: string
                  clusterServicePlanExternalID:
                    type: string
                  servicePlanExternalName:
                    type: string
                  servicePlanExternalID:
                    type: string
                  parameters:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  parameterChecksum:
                    type: string
                  userInfo:
                    type: object
                    properties:
                      username:
                        type: string
                      uid:
                        type: string
                      groups:
                        type: array
                        items:
                          type: string
                      extra:
                        additionalProperties:
                          items:
                            type: string
                          type: array
                        type: object
              provisionStatus:
                type: string
              deprovisionStatus:
                type: string
              defaultProvisionParameters:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              lastConditionState:
                type: string
              userSpecifiedPlanName:
                type: string
              userSpecifiedClassName:
                type: string
    additionalPrinterColumns:
      - name: Class
        type: string
        jsonPath: .status.userSpecifiedClassName
      - name: Plan
        type: string
        jsonPath: .status.userSpecifiedPlanName
      - name: Status
        type: string
        jsonPath: .status.lastConditionState
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
