apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceplans.servicecatalog.k8s.io
  labels:
    svcat: "true"
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: servicecatalog.k8s.io
  scope: Namespaced
  names:
    plural: serviceplans
    singular: serviceplan
    kind: ServicePlan
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              externalName:
                type: string
              externalID:
                type: string
              description:
                type: string
              bindable:
                type: boolean
              free:
                type: boolean
              externalMetadata:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              instanceCreateParameterSchema:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              instanceUpdateParameterSchema:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              serviceBindingCreateParameterSchema:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              defaultProvisionParameters:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              serviceBrokerName:
                type: string
              serviceClassRef:
                type: object
                properties:
                  name:
                    type: string
          status:
            type: object
            properties:
              removedFromBrokerCatalog:
                type: boolean
    additionalPrinterColumns:
      - name: External-Name
        type: string
        jsonPath: .spec.externalName
      - name: Broker
        type: string
        jsonPath: .spec.serviceBrokerName
      - name: Class
        type: string
        jsonPath: .spec.serviceClassRef.name
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
